### ISSUE TITLE
Overriding routes 

### ISSUE THREAD

**Issue by jamestagal** [jamestagal/edtechdesigner#10]
Hi Jim,
When changing the routes as you showed in your video _Using Plenty to make a simple Svelte static site_ to use the title post of a field, it doesn’t work for me. I tried adding the following code to the plenti.json file but it still uses the file extension as its name.

```
"posts": "posts/:field(title)",
```

**Comment by jimafisk** [comment]
The API was update to use `:fields()` instead of `:field()` is `v0.4.x`: https://github.com/plentico/plenti/issues/119 

So the following should work:

```json
"posts": "posts/:fields(title)",
```

**Comment by jamestagal** [comment]
Thanks Jim. That fixed it 👍
