### ISSUE TITLE
Issue when trying to incorporate featured.svelte update

### ISSUE THREAD

**Issue by jamestagal** [jamestagal/edtechdesigner#19]
Hi @roobyz 
When using your changes from the **featured.svelte** file [commit you made on 18th Jan](https://github.com/plenti-themes/compendium/commit/9d8dc8fd67c170aa34a479b035a35ea9ae039d26), caused an error.

The error was : 
```
javascript stack trace: TypeError: Cannot read property 'indexOf' of undefined
    at create_ssr:45:71
    at each (create_ssr:1521:16)
    at create_ssr:45:7
    at Object.$$render (create_ssr:1555:22)
    at create_ssr:79:112
    at each (create_ssr:1521:16)
    at create_ssr:70:17
    at Object.$$render (create_ssr:1555:22)
    at create_ssr:41:136
    at Object.$$render (create_ssr:1555:22) (File: /home/runner/work/plenti/plenti/cmd/build.go, Line: 140)
```

The code I am using is [linked here:](https://github.com/jamestagal/edtechdesigner/blob/main/layouts/components/featured.svelte)

I am not sure what is the cause of this error. Pls have a look when you can.

Best regards,
Ben

**Comment by roobyz** [comment]
Hi @jamestagal ,

This is related to the change that I made to address your issue: https://github.com/jamestagal/edtechdesigner/issues/18

Let me know if my note there doesn't guide the way. ;-)

Cheers,
Roberto

**Comment by jamestagal** [comment]
Hi @roobyz 

Ok thanks. Maybe I don't understand the intricacies of what is in these change but It was concerned because I was incrementally adding/incorporating each and every commit from those you made on the 18th, and adding all worked except the ```featured.svelte``` file changes and ```cards_projs.svelte```
So what would be the best way forward? 
1. refresh the theme to get the latest changes
2.  merge those changes into my version

Cheers,
Ben

**Comment by roobyz** [comment]
Hi @jamestagal ,

I recommend you:
1. refresh the theme to get the latest changes
2. then overwrite any of your custom layout/*.svelte files from the theme folder to your project folder
3. Afterward, you can see the diffs (changes) side-by-side between your project and latest template via git... and then add back any of  your customizations that you want to keep.

Cheers,
Roberto

**Comment by roobyz** [comment]
BTW... I am incorporating the sort function into the template that we discussed. And updating the project sort functionality so that it is easy to set the sort approach by date or name using parameters. Hopefully this will make it easier for you going forward. I like to implement generic approaches that work broadly. ;-)

**Comment by jamestagal** [comment]
yes thanks @roobyz that sounds great. :)

Just to clarify step 2, from above.
when you mean 'overwrite' do you mean replace? are you saying to copy the content of each of those new files and paste into my custom layout/*.svelte files ? 
The way I was doing this from your first set of commits from the 18th was to:

- First refreshed the theme
- Then in VS Code; went to Source Control and found the files I had modified in my project in those in your new commits.  
- Then opened it which shows both versions old and new side-by-side (highlighting red = removed/deleted and green = new/added)
- Then opened the same file from my project which I have modified. 
-  Compared your additions and Incorporated your changes into mine line by line 

Maybe I could be doing this a better way or more efficiently. Pls let me know :)

**Comment by roobyz** [comment]
great question... yes, replace the file... because then when you open the file using the "source control" feature of VSCode, you will automatically get the side by side comparison.
You can then copy over any changes from the left pane (your version) to the right pane and edit in place. And then if you don't want to accept any of the changes you can revert the whole file from the object explorer to get back to where your started. Total win-win! ;-)

**Comment by jamestagal** [comment]
ok thanks for explaining because when i opened the 'source control" I was only seeing the older version of the files in the Theme folder not the side by side comparison of my files. I thought if I replace my files with the new ones I wouldn't be able to see the changes I had made to my files and would lose them forever!!! 
Maybe I need to find a Youtube video on how to do this properly :)

**Comment by roobyz** [comment]
the beauty of it is that with git, you can always revert to where you were... instant undo. ;-)

**Comment by jamestagal** [comment]
Hi @roobyz
This time I tried the command ```plenti theme update comdendium``` and got the following message.
 ```
Could not find URL for theme, fix theme_config in plenti.json
 ```
But the url is correct in my theme_config file.
```svelte
{
	"build": "public",
	"baseurl": "/",
	"theme": "compendium",
	"theme_config": {
		"compendium": {
			"url": "https://github.com/plenti-themes/compendium",
			"commit": "cbc6ceed503735ad364937cca5a66a24c49987bc"
		}
	},
 ```
That's strange because it worked the last time I did it!

UPDATE: Hi @jimafisk I am still getting this message about not being able to find the URL for the theme when trying to update the theme.  Do you have any ideas here? I have started and stopped running the local server but the issue persists. Would updating the Plenti binary make any difference?
Cheers,
Ben

**Comment by roobyz** [comment]
hi @jamestagal ,

I just pushed the generic sorting changes. Please try again now. Wondering if there was some issue on Jim's site. If it doesn't work again we may need to check with him.

The latest update includes an updated version of jim's sort function and subsequent changes. You need to set your function parameters as desired for example `sortByDate(allPosts, "modified", "oldest")`, where:

```
var sortDate = typeof sortDate != "undefined" ? order : "created";
var order = typeof order != "undefined" ? order : "newest";
```

Also, I updated the project sorting to cover your use-case and mine. I updated `content/index.json` to include a new key which you should put into the "themes" section, about line 17. See the new file for reference if needed:

```
"projsSort": "Date",
"projsSortValues": "Date, Name",
```

Also, I included a TLDR boolean in the `cards_proj.svelte` file, which you may want to set to `false`. Let me know if you prefer a flag in the `content/index.json` file.

Cheers,
Roberto

**Comment by jimafisk** [comment]
@jamestagal - It looks like you're misspelling the theme name in your update command. [Above](https://github.com/jamestagal/edtechdesigner/issues/19#issuecomment-1018251434) you mentioned running:
```
plenti theme update comdendium
```
but it should be:
```
plenti theme update compendium
```
Note the "d" in your command is actually a "p." Hope that helps!

**Comment by jamestagal** [comment]
Hi @jimafisk 
Yes it was staring me in the face!! What an oversight! Thanks for picking that up.

Best regards,
Ben

**Comment by jamestagal** [comment]
Hi @roobyz and @jimafisk 

I have successfully been able to update the theme with the latest commits and incorporated change to my modified files. 

Thank you very much for this work, I really appreciated your time and effort.

Best regards,
Ben
