### ISSUE TITLE
Get the h5p resizer.js working

### ISSUE THREAD

**Issue by jimafisk** [jamestagal/edtechdesigner#2]
> H5P conveniently provides an iframe resizer which is a javascript helper file that is added to my hosted account. So I have created a `h5p.svelte` file in the `scripts` folder but I don't have enough knowledge of how to import or get it into the `post.svelte` file for it to work and resize the iframe properly.  See h5p.svelte file below
```svelte
<script
 src="https://edtechdesigner.h5p.com/js/h5p-resizer.js" charset="UTF-8">
</script>
```
> See screenshot of the embedded iframe not resized.

![svelte](https://user-images.githubusercontent.com/5913244/147571549-f1357095-ba82-4a38-a5f0-37533cefa116.png)

> If you could help me get this working I would really appreciate it.

**Comment by jimafisk** [comment]
Moving this script into the `<head>` of the project should solve this. See https://github.com/jamestagal/edtechdesigner/pull/8

<details>
<summary>See screenshot</summary>

![iframe](https://user-images.githubusercontent.com/5913244/147597997-71234bc9-e62e-4d40-a9c6-a93118ff1b4d.png)


</details>

**Comment by jamestagal** [comment]
Hi Jim. thank you.
I have added it as you suggested and all is good. 👍 
```
<head>
  <script
 src="https://edtechdesigner.h5p.com/js/h5p-resizer.js" charset="UTF-8">
  </script>
</head>
```
