### ISSUE TITLE
Accent underline not persistent on Posts page in navbar 

### ISSUE THREAD

**Issue by jamestagal** [jamestagal/edtechdesigner#22]
Hello @roobyz 

I noticed that all route pages get the accented underline except for the Posts page.  See screenshot below.

![Screen Shot 2022-01-26 at 1 50 10 pm](https://user-images.githubusercontent.com/6309595/151095946-22cc3a3d-ac72-4125-bd37-4d843913969d.png)

Do you know what could be causing this issue? Is it related to the undefined element [issues ](https://github.com/jamestagal/edtechdesigner/issues/21) ?

Please have a look when you can.

Thanks Ben

**Comment by roobyz** [comment]
Hi @jamestagal 

Ahh, your changes sort of created or highlighted a "bug", depending on how you want to look at it.

I noticed that rather than changing the title from "Project" to "Post" in the "_content\proj\\**projs**.json_" and "_navbar.svelte_", you renamed the file "_content\proj\\**projs**.json_" to "_content\proj\\**posts**.json_"... as a result, the logic that was using `content.path` to set the `active` CSS attribute stopped working.

That said, I believe that the best solution would be to switch from `content.path` to `content.type`. For example, lines 104 to 113 in the navbar.svelte would be:

``` svelte
          <a class="block md:inline-flex px-2 py-1 md:py-0" href="."
            ><span class="navmenu{content.type == 'index' ? ' active' : ''}"
            >Home</span
          ></a
          >
          <a class="block md:inline-flex px-2 py-1 md:py-0" href="posts/"
            ><span class="navmenu{content.type == 'projs' ? ' active' : ''}"
            >Posts</span
          ></a
          >
```
I will apply that fix to the template. 

I've noticed that some of your changes were much more "brute force" than required and is causing extra work. You might want to refactor your project so that it is easier for you to maintain and customize going forward. Let me know if it would make sense to discuss over Zoom sometime.

Cheers,
Roberto

**Comment by jamestagal** [comment]
Hi @roobyz 

Yes I see the problem. It might be easier to return / refactor it back to something more maintainable for me.
I would really appreciate discussing it when you are free. I live in the capital city of Australia, Canberra which is in the Australian Eastern Daylight Time zone (GMT+11). I work from home so I am very flexible in terms of a time.  Please let me know a day and time that suits you.

UPDATE: changing from ```content.path``` to ```content.type``` and changing the ```'/'``` to  ```'index'``` for the Home page route worked as you mentioned above.  :) Thank you

Best regards,
Ben

**Comment by roobyz** [comment]
Hi @jamestagal,,

I'm glad it worked.

I am familiar with Canberra. I lived in Brisbane for 18 months while working for Suncorp Group. Did a bit of travel to Sydney and Melbourne. ;-) I'm on San Francisco time. I think it is about 19 hours difference. My schedule during the work week is rather crazy. A good time for me might be:

- 9 or 10pm, which would be 4 or 5pm in the future for you
- 2 or 3pm, which would be 9 or 10am in the future for you

Best,
Roberto

**Comment by jamestagal** [comment]
Hi @roobyz 
Great! I think 3pm San Francisco time would work for me. Please schedule me in when you can.. :)

Best regards,
Ben

**Comment by roobyz** [comment]
hi @jamestagal,

A lot of what happens in the code is a result of working on arrays of objects. Some quick tutorials that might be helpful to level up:

* working with the [spread operator](https://www.samanthaming.com/tidbits/92-6-use-cases-of-spread-with-array/)
* working with [arrays](https://www.digitalocean.com/community/tutorial_series/working-with-arrays-in-javascript)

Cheers,
Roberto

**Comment by jamestagal** [comment]
Hi @roobyz 
Thanks for the links to these tutorials.. They are well explained with clear examples. 
I also have been trying out [https://grasshopper.app/](url) a Google created app for learning coding and it is quite a good beginner course because it really scaffolds the fundamental concepts with practical code activities and challenges getting you to apply your knowledge and write mini code snippets to solve real problems. 
Cheers,
Ben

**Comment by jamestagal** [comment]
Hi @roobyz 
Also let me know when you would be able to meet! My questions are building. :)
But also I have been implementing a couple of design features into my app.

1. adding articleSnap (to give an overview of each post in the Posts list) See an example on **Resume** post from the [Posts](https://vigorous-einstein-b90548.netlify.app/posts/) page
2. adding new look Categories and Tags layout 

Also I found a little bug with the loading of Categories and Tags in the process; they are not updating when moving from Tag to Tag or Category to Category. I will post this one as an issue so you can look at it.

Cheers,
Ben

**Comment by roobyz** [comment]
hi @jamestagal 
Let me know if you are available today. I have some time around 2pm to 3pm, which is about 9am -10am your time.
Cheers,
Roberto

**Comment by jamestagal** [comment]
Hi @roobyz 
Great. I can meet today but from 2:30pm your time if that's ok? I have to drop my son off at school at 2pm (9am here) 
Let me know if that is still ok for you.

Cheers,
Ben

**Comment by roobyz** [comment]
hi @jamestagal ... works for me.  Let's try... https://meet.google.com/dbd-mhaa-mep

**Comment by jamestagal** [comment]
Hi @roobyz 
Thanks for your time...Sorry I froze and had to join again but you must have left already...Thanks again for your time and great work! much appreciated..I think I can implement my changes in a more efficient ways now..

Cheers,
Ben

**Comment by roobyz** [comment]
hi @jamestagal ,
Great catching up Ben. No worries. Have fun on the theme enhancements. As discussed, I've already committed the fixes for the bugs you mentioned on our call. In addition, I've updated the search component to work on both titles and body content.

Cheers,
Roberto
