### ISSUE TITLE
Remove commas between Tags

### ISSUE THREAD

**Issue by jamestagal** [jamestagal/edtechdesigner#26]
Hello @roobyz

I would like to remove the commas between tags as my styling of tag are in containers and they don't warrant having commas separating these tags however I can't find where they are? which files they are located in? I thought it might have been in the ```post_meta.svelet``` file in the following location: 
```svelte
</a>{#if i < tags.length - 1},{/if}</div>
```
But if i remove that comma here throws an error.

Could you please point me in the right direction. 
Regards,
Ben

**Comment by roobyz** [comment]
You need to remove the `if` statement. The following should work:

``` svelte
</a></div>
```

**Comment by jamestagal** [comment]
Thank you @roobyz 

Yes i see. :)
