### ISSUE TITLE
Using the Styles

### ISSUE THREAD

**Issue by jimafisk** [jamestagal/edtechdesigner#3]
> In the `index.json` file I have tried swapping out the default Earthliness colourScheme with one of the others (Simplicity, Technobeat) to see what they look like but changing the name in the value for the colorScheme doesn't seem to work. Is this the only place I need to change it to see a change? Please let me know if I am doing something wrong here.

**Comment by jimafisk** [comment]
It looks like @roobyz (the designer of Compendium) set up NPM scripts in `package.json` to do things like change the color scheme: https://github.com/plenti-themes/compendium/blob/864bb3e13459fb1ce7123d1e8b79e3ff281de3b2/package.json#L5

<details>
<summary>See the color-scheme script</summary>

```
"cp styles/$(grep -m 1 colorScheme content/index.json | awk '{ gsub(/[[:punct:]]/, \"\"); print $2 }').css assets/color-scheme.css"
```
</details>

So in order for this to work:
- Copy the scripts to your project folder: `cp themes/compendium/package.json package.json`
- Create the destination to write the color scheme CSS variables to: `mkdir assets && touch assets/color-scheme.css`
- Give the script access to the original variables: `cp -R themes/compendium/styles .`

Then run the script: `npm run update:scheme`

<details>
<summary>See Technobeat screenshot</summary>

![technobeat](https://user-images.githubusercontent.com/5913244/147593207-ce503901-56dd-4aa7-8c14-2aa7245359ee.png)

</details>

**Comment by jimafisk** [comment]
This is how you would implement technobeat: https://github.com/jamestagal/edtechdesigner/pull/9

**Comment by jamestagal** [comment]
Thank you Jim. I followed your steps and changing the colorScheme in index.json works now. One thing I didn't know is that i have to copy over the style from the scheme into the color-scheme.css and then update the colorScheme name as well for it to take affect.

**Comment by roobyz** [comment]
Sorry for my delayed response, it has been a bit hectic quarter with my new job and all. I am working on refining the theming process. I have an idea for simplifying things, but have no working code yet. Will keep you posted.
