### ISSUE TITLE
failed build step in Github

### ISSUE THREAD

**Issue by jamestagal** [jamestagal/edtechdesigner#34]
Hi @jimafisk 
I just committed my changes to Github and get an error. see below. It mentioned ``` Ubuntu-18.04 environment is deprecated```.
Could you please take a look when you can.

https://github.com/jamestagal/edtechdesigner/actions/runs/4541930120

Could you please take a look when you can?
P.S. I have added you as a collaborator on this repo.

Thanks
Ben

**Comment by jimafisk** [comment]
Sounds like you need to use a newer operating system for your runner: https://github.com/jamestagal/edtechdesigner/blob/main/.github/workflows/netlify-deploy.yml#L10

Probably something like:
- `ubuntu-20.04`
- `ubuntu-22.04`
- `ubuntu-latest`

**Comment by jamestagal** [comment]
Thanks @jimafisk 
Yes an easy fix in this case. appreciate it :)
Ben
